print("Welcome to the Band name Generator")
city_name = input("What is your city name?\n")
pet_name =  input("What is your dog name?\n")
print("Your band name could be: " + city_name + " " + pet_name)
print("This is a git test")